### PR TITLE
Gazetteer cleanup listener

### PR DESCRIPTION
**Pull request by hkkenneth**
For #25

### CODE REVIEW

**Comment by mbelousov** [comment]
@hkkenneth, great! Well done! Just thinking, do we need to have something similar to clean output directory before job execution (to remove outputs from previous run)? @healtex/deid

**Comment by hkkenneth** [comment]
It can be easily done with a `beforeJob()` method with an almost identical implementation - do we have any use cases which we may want to keep the files from the previous run?

**Comment by hkkenneth** [comment]
On a different note, I think in the future, we could have a configuration to let advanced users keep the gazetteer files **after** the job: to inspect them, or to use the files to customize their own gazetteers?

**Comment by mbelousov** [comment]
@hkkenneth For the first version (consider the desktop application) we could just use name of the input folder and then create corresponding folders: {name}-gazetteers (for step1) and {name}-results (for step2) in that case we will be able to run multiple instances of app (e.g. processing two datasets at the same time).
Agree that it might be a good idea to keep gazetteers, so we can a corresponding option to our workflow and in the desktop app we could have a checkbox.

**Comment by hkkenneth** [comment]
What's {name} here? But can't users already achieve the same effect with separate workspace?

**Comment by mbelousov** [comment]
@hkkenneth , yep, workspace sounds like a better option.

**Pull request merged**
